### ISSUE TITLE
size.width < 1 || size.height < 1还是size.width < 1 && size.height < 1 ？

### ISSUE THREAD

**Issue by BeatsKitano** [ibireme/YYAsyncLayer#16]
if (size.width < 1 || size.height < 1) {
            CGImageRef image = (__bridge_retained CGImageRef)(self.contents);
            self.contents = nil;
            if (image) {
                dispatch_async(YYAsyncLayerGetReleaseQueue(), ^{
                    CFRelease(image);
                });
            }
            if (task.didDisplay) task.didDisplay(self, YES);
            CGColorRelease(backgroundColor);
            return;
        }
这段代码的意思是？

**Comment by xll503721** [comment]
这段代码主要是意思在于`dispatch_async(YYAsyncLayerGetReleaseQueue(), ^{
CFRelease(image);
});`
将self.contents的内容在非当前线程进行释放，猜想是可能有些情况下，比如一个view，只是创建出来但没有对其frame进行赋值时，其实你也不想让他显示，他就帮你把contents释放掉，这样一来，省点内存，而且又不必要对这个contents干嘛，省事。
