### ISSUE TITLE
关于CreateCTLines()函数的疑问

### ISSUE THREAD

**Issue by wave113** [ibireme/YYAsyncLayer#19]
readme.md里面的简单用法介绍里, 在- (YYAsyncLayerDisplayTask *)newAsyncDisplayTask 方法里有一个名为CreateCTLines()的函数, 请问这个函数是被包括在某个系统库里吗?

**Comment by BoxDengJZ** [comment]
https://github.com/ibireme/YYAsyncLayer/issues/20
