### ISSUE TITLE
It is better to use [UIScreen -nativeScale] instead of [UIScreen -scale].

### ISSUE THREAD

**Issue by WeZZard** [ibireme/YYAsyncLayer#3]
In YYAsyncLayer's -init method:

scale = [UIScreen mainScreen].scale;

is better to be changed into:

scale = [UIScreen mainScreen].nativeScale;

in post-iPhone-6-Plus age.

**Comment by ibireme** [comment]
When generate a bitmap image and display it with UIKit, it's better to use an integer scale value.
See this discussion: https://github.com/AFNetworking/AFNetworking/issues/2830
