### ISSUE TITLE
[self setNeedsDisplay] 无效

### ISSUE THREAD

**Issue by KittenYang** [ibireme/YYAsyncLayer#4]
``` objc
- (void)contentsNeedUpdated {
    // do update
    [self setNeedsDisplay];
}
```

此处地方`self setNeedsDisplay`无效。我也纳闷，因为 view 的 setNeedsDisplay 会自动转发到 layer 的 setNeedsDisplay，而 `layerClass` 已经指定了 `YYAsyncLayer` ,按理应该能转发到。请教原因。另外，改成`[self.layer setNeedsDisplay]` 解决。

**Comment by ibireme** [comment]
这可能是 YYTransaction 调用这个方法的时机导致的？如果用 YYTransaction 调用这个方法，它会在 RunLoop 中 CATransaction 结束后得到回调，也许会导致 UIView 忽略这个方法？

我在 readme 里写的那些只是示意，没有跑过，可能有问题吧。我改一下。
