### ISSUE TITLE
使用 YYAsyncLayer 异步绘制图片内存占用高的问题

### ISSUE THREAD

**Issue by KittenYang** [ibireme/YYAsyncLayer#5]
YY 大神你好，我尝试着对你的微博 List 进行了优化，cell 上的一些细小的视图（比如人名、日期、来源等）这些控件使用了 YYAsyncLayer 异步绘制成了 `layer` 的 `contents`，减少了视图层级，在流畅性上获得了很好的提升。虽然我用 Xcode 的 Debug Session 查看发现即使的暴力滑动的情况下内存依然控制在 20M 左右，但是使用 Instruments 的 Allocations 一调试，发现 `UIGraphicsBeginImageContextWithOptions ` 和 `UIGraphicsGetImageFromCurrentImageContext ` 两个方法内存占用竟然有几百兆。

<img width="1017" alt="2016-03-08 4 30 26" src="https://cloud.githubusercontent.com/assets/5517281/13596268/77c139e2-e54c-11e5-90f2-765049a1977b.png">

我尝试在 SO 上寻找解决方案，试着给绘制代码加了 autoreleasepool

```objc
    task.display = { [weak self] (context, size, isCancelled) in
      if isCancelled() {
        return
      }
      autoreleasepool({ () -> () in
        self?.draw(context,size: size) // 这里是具体的绘制代码
      })
    }
```

draw 的具体代码类似如下：
```objc
  private func draw(context: CGContextRef, size: CGSize) {
    //background color
    kWeiboStatusViewBackgroundColor.set()
    CGContextFillRect(context, CGRect(x: 0, y: 0, width: size.width, height: size.height))
    
    //timeline
    kWeiboStatusViewTimelineColor.set()
    CGContextFillRect(context, CGRectMake(kWeiboStatusCellLeftMargin+kWeiboStatusCellAvatarSize/2, 0, 1, height))
  
    //...
    retweetIcon.drawInRect(iconRect)
    //...
    retweetString.drawAtPoint(CGPoint(x: iconRect.origin.x + 3 + iconRect.width, y: retweet ? (iconRect.origin.y - 4) : (iconRect.origin.y - 3)))

  }
```
可是无果。想请教您指点，感谢。

**Comment by KittenYang** [comment]
另外我发现 YYLabel 打开异步绘制的时候就没有内存占用高的问题，我尝试看了 YYLabel 的异步实现原理，唯一发现和我的代码结构不同的地方在于您使用了
```objc
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, point.x, point.y);
    ...
    CGContextRestoreGState(context);
```
我不知道是不是这个原因。
另外问一下：既然异步可以实现流畅性质的飞跃，为什么在设计之初还要留一个接口`displaysAsynchronously` 并默认为`NO`。难道异步有什么代价吗？

**Comment by ibireme** [comment]
关于绘制内存占用高的问题，可以试试在 YYAsyncLayer 里面，从 `UIGraphicsBeginImageContextWithOptions` 到 `UIGraphicsEndImageContext` 之间的代码，包括这两行，都用 autorelease 包起来看看。如果能解决的话那我更新一下，如果还解决不了，那我猜可能是 context 或 image 被其他地方 retain 没有被及时释放掉，比如 CALayer.contents。

开启异步绘制的代价是内容更新延迟、总资源占用提升。例如当调用了 `label.text = xxx` 后，异步绘制完成后，界面上显示的内容才会更新，如果这个时间超过了 1/60s，那用户就会看到空白、或者很短的渐变动画（取决于 label 的那几个异步绘制属性配置）。另外，相对于同步绘制来说，异步绘制会多出不少线程间切换等资源消耗，所以总的 CPU 占用还是会高一些。

**Comment by KittenYang** [comment]
@ibireme  请问你说的 autorelease 是 @autoreleasepool 吗？另外如果 ：
```objc 
@autoreleasepool {
            UIGraphicsBeginImageContextWithOptions(size, opaque, scale);
            CGContextRef context = UIGraphicsGetCurrentContext();
            task.display(context, size, isCancelled);
            if (isCancelled()) {
              UIGraphicsEndImageContext();
              dispatch_async(dispatch_get_main_queue(), ^{
                if (task.didDisplay) task.didDisplay(self, NO);
              });
              return;
            }
            UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
            UIGraphicsEndImageContext();
  }
```
这样包起来后，下文无法获取 image 了。

**Comment by ibireme** [comment]
UIImage *image = nil;
    @autoreleasepool {
        UIGraphicsBeginImageContextWithOptions(size, opaque, scale);
        CGContextRef context = UIGraphicsGetCurrentContext();
        task.display(context, size, isCancelled);
            if (isCancelled()) {
              UIGraphicsEndImageContext();
              dispatch_async(dispatch_get_main_queue(), ^{
                  if (task.didDisplay) task.didDisplay(self, NO);
              });
              return;
        }
        image = UIGraphicsGetImageFromCurrentImageContext();
        UIGraphicsEndImageContext();
    }

**Comment by KittenYang** [comment]
@ibireme 我以为使用局部变量就无法被 autoreleasepool 作用了。恩，内存问题解决。

**Comment by KittenYang** [comment]
@ibireme  YY 大神我又来了。今天又发现，加了`autoreleasepool`有了几百兆的内存，不加反而正常。还有我想问一下这个 Persistent Bytes 和 Total Bytes 有什么区别？为什么 Total Bytes 这么大？谢谢！
![2016-03-11 3 41 16](https://cloud.githubusercontent.com/assets/5517281/13696221/d7dbf8a8-e79f-11e5-9a3e-0ce39ecdc413.png)

**Comment by ibireme** [comment]
呃。。具体你还是查下文档吧。。我不太了解，解释也不一定对。。
看大致的内存占用我更习惯用 Activity Monitor。

**Comment by KittenYang** [comment]
抱歉，还是没忍住问了这种问题，关于 Persistent Bytes 和 Total Bytes 的问题已经解决，下次不会再问类似的问题了。

**Comment by zzyspace** [comment]
发现UIGraphicsBeginImageContextWithOptions这个方法, 传入的 size 只要过大, 就会占用几百兆的内存, 不懂有没有代替方法...

**Comment by Tbwas** [comment]
遇到同样的问题，使用@autoreleasepool 将代码包起来，还是占用很大内存，貌似没啥效果

**Comment by MoShenGuo** [comment]
autoreleasepool{
 UIGraphicsBeginImageContext(size)
            topImageView?.image?.draw(in: CGRect(x: 0, y: 0, width: size.width, height: size.height))
            if let paths = pathArray {
                for path in paths {
                    UIGraphicsGetCurrentContext()?.move(to: CGPoint(x: path.startPoint.x, y: path.startPoint.y))
                    UIGraphicsGetCurrentContext()?.addLine(to: CGPoint(x: path.startPoint.x, y: path.startPoint.y))
                    for point in path.pathPointArray {
                        UIGraphicsGetCurrentContext()?.addLine(to: CGPoint(x: point.xPoint, y: point.yPoint))
                    }
                }
                UIGraphicsGetCurrentContext()?.setLineCap(.round)
                UIGraphicsGetCurrentContext()?.setLineWidth(lineWidth * rate)
                UIGraphicsGetCurrentContext()?.setBlendMode(.clear)
                UIGraphicsGetCurrentContext()?.strokePath()
            }
            //获取画图后图片
            let finalPath = UIGraphicsGetImageFromCurrentImageContext()
            UIGraphicsEndImageContext()
}
yy大神,加上自动释放并没有用的,我现在做打马赛克,每次touchesEnded结束都会画一次,会导致内存暴涨,怎么去解决呢

**Comment by caohrong** [comment]
这个问题最终解决了吗？我其实用的不是YYAsynLayer，但是也有异步绘制内存暴涨的问题。😂
