### ISSUE TITLE
请教一个关于计数器 YYSentinel 的问题

### ISSUE THREAD

**Issue by KittenYang** [ibireme/YYAsyncLayer#6]
在看源码的过程中，对及时退出绘制任务的实现方案的理解有点拿不准，特来求证一下。
首先我一直很好奇，什么时候会 `value != sentinel.value;`，换言之，得滑到多快，才能让 `value != sentinel.value;`？

源码里面，只要 cell 出现在屏幕上，都会触发一次 `setNeedsDisplay`:
```objc
- (void)setNeedsDisplay {
    [self _cancelAsyncDisplay]; //1
    [super setNeedsDisplay]; //2
}
```
这里面，//1 处会让计数器加1，我们可以把它认为是标准值；//2 里面会做一次取值：
```objc
YYSentinel *sentinel = _sentinel;
int32_t value = sentinel.value; //3
```
而由于 1、2 操作都是在主线程做的，所以会按先后顺序来。

所以，我的结论就是，源码中只是利用了函数调用的时间差，也就是说，只有当滑动的速度比 1、3 两处函数调用的时间差还要快，才会触发 `isCancelled` 判断条件。

以上是我的理解，不知道是否正确，特来求证，望指教。

PS：另外，还有一点想法，源码中的 `isCancelled` 属于主动式获取，必须去调用才知道是否不一致了，不太精准，容易漏掉。有没有可能实现被动式通知，就是一旦触发 `value != sentinel.value;` 就通知线程退出呢？

**Comment by ibireme** [comment]
sentinel 的逻辑大概是这样：

        YYSentinel *sentinel = _sentinel;
        int32_t value = sentinel.value;
        BOOL (^isCancelled)() = ^BOOL() {
            return value != sentinel.value;
        };

首先 sentinel 和当时那一刻的 value 会被 capture 到 isCancelled 的 block 内，一旦该 block 创建后，block 内的 value 就不会改变了。在这之后一旦 sentinel 发生改变，isCancelled 就会返回 YES。

isCancelled 最终会被传递到绘制代码中，供其判断。从代码提交 queue 到代码执行完毕这一段时间内，外面 layer 可能已经被要求重绘了，这时 isCancelled 就会触发。这在 TableView 快速滑动时还是触发得很频繁的。

那个通知后线程立刻退出的操作，够呛能做到。。

**Comment by KittenYang** [comment]
@ibireme  你的解释我理解。就像你说的：“外面 layer 可能已经被要求重绘了”，但是因为重绘的时候让 sentinel +1 ，之后 value 也会被立刻更新。所以如果在这段时间段内调用 isCancelled 就会产生 value 依然是上一次的值，但是 sentinel 已经 +1 了的情况，就会返回 YES，否则两者的值又相等了。所以还是利用了两次赋值的时间差，对吗？

**Comment by D-Wang** [comment]
ibireme这里的isCancelled实现与NSOperation类似，当一个operation加入队列后，这个operation即使被cancel，也并不会被从队列中移除，当operation的main函数被调用时，main的实现中判断是不是isCancelled，并决定是否直接返回。回到这个问题，isCancelled这个block在创建的时候就捕获了value的值，这个值不会再改变，sentinel被捕获的是引用。所以这里的时间差应该是isCancelled被创建的时间，和每次被调用的时间的时间差。

**Comment by KittenYang** [comment]
@D-Wang 也就是说一个队列只会对应唯一一个 isCancelled，下次提交到新 queue 的 isCancelled 已经是新创建的 isCancelled 了？而由于每个 isCancelled 都捕获了 value ，所以在一个 queue 里面得到的 value 始终是不变的，而 sentinel.value 很可能已经变了。Am I right?

**Comment by D-Wang** [comment]
@KittenYang 一个Operation/Task对应唯一一个isCancelled，在NSOperation中是函数调用，在这里是这个isCancelled block。所以每次提交到queue的task的isCancelled block是不同的block对象，其中捕获的value的值都是这个task创建时sentinel.value的值，而捕获的sentinel的引用都是这个layer的sentinel的引用，最后在block执行的时候，value的值就是捕获的value，而sentinel.value则可能已经发生了变化。

**Comment by KittenYang** [comment]
@D-Wang  Make sense!
